In [8]:
import pandas as pd

In [9]:
import os
base_dir = './res/'
dir = os.path.join(base_dir, '')
dir

'./res/'

In [10]:
data = os.listdir(dir)
data

['골프장현황.csv',
 '공연장현황.csv',
 '공중화장실현황.csv',
 '관공서현황.csv',
 '대규모점포현황.csv',
 '박물관·미술관.csv',
 '숙박업소현황.csv',
 '시장및마트현황.csv',
 '아파트주차장.csv',
 '영화상영관현황.csv',
 '음식점.csv',
 '응급의료기관.csv',
 '의원현황.csv',
 '일반음식점.csv',
 '주차장정보현황.csv',
 '폐기물처리업체현황.csv']

In [11]:
df_all = pd.DataFrame(columns=['소재지명', '도로명', '위도', '경도', '시설구분'])
df_all

Empty DataFrame
Columns: [소재지명, 도로명, 위도, 경도, 시설구분]
Index: []

In [12]:
for i in range(len(data)):
    df_all = pd.concat([df_all, (pd.read_csv(dir+data[i]))], ignore_index=True)
df_all

,소재지명,도로명,위도,경도,시설구분,Unnamed: 0
0,플라자(한화호텔앤드리조트㈜),경기도 용인시 처인구 남사면 봉무로 153번길 79,37.129816,127.148139,골프장,0.0
1,골드(기흥관광개발),경기도 용인시 기흥구 기흥단지로 398,37.217948,127.136339,골프장,1.0
2,태광(태광관광개발),경기도 용인시 기흥구 흥덕4로 77,37.278537,127.089073,골프장,2.0
3,태광대중(태광관광개발),경기도 용인시 기흥구 흥덕4로 77,37.278537,127.089073,골프장,3.0
4,한원(한원),경기도 용인시 처인구 남사면 전나무골길 2번길 94,37.153984,127.125162,골프장,4.0
...,...,...,...,...,...,...
10912,백옥영농조합,경기도 용인시 처인구 백암면 박곡로216번길 33,37.175227,127.401301,폐기물처리업체,266.0
10913,㈜케이블테크,경기도 용인시 처인구 남사면 각궁로 126,37.10104,127.154195,폐기물처리업체,267.0
10914,주식회사 신광상사,경기도 용인시 처인구 백암면 죽양대로 870-4,37.143541,127.389249,폐기물처리업체,268.0
10915,㈜남강엠앤테크,경기도 용인시 처인구 이동읍 서리로 185,37.195412,127.16996,폐기물처리업체,269.0
10916,하늘유통,경기도 용인시 처인구 백령로 34-8,37.263883,127.193177,폐기물처리업체,270.0

In [13]:
df_all = df_all.drop(['Unnamed: 0'], axis=1)
df_all

,소재지명,도로명,위도,경도,시설구분
0,플라자(한화호텔앤드리조트㈜),경기도 용인시 처인구 남사면 봉무로 153번길 79,37.129816,127.148139,골프장
1,골드(기흥관광개발),경기도 용인시 기흥구 기흥단지로 398,37.217948,127.136339,골프장
2,태광(태광관광개발),경기도 용인시 기흥구 흥덕4로 77,37.278537,127.089073,골프장
3,태광대중(태광관광개발),경기도 용인시 기흥구 흥덕4로 77,37.278537,127.089073,골프장
4,한원(한원),경기도 용인시 처인구 남사면 전나무골길 2번길 94,37.153984,127.125162,골프장
...,...,...,...,...,...
10912,백옥영농조합,경기도 용인시 처인구 백암면 박곡로216번길 33,37.175227,127.401301,폐기물처리업체
10913,㈜케이블테크,경기도 용인시 처인구 남사면 각궁로 126,37.10104,127.154195,폐기물처리업체
10914,주식회사 신광상사,경기도 용인시 처인구 백암면 죽양대로 870-4,37.143541,127.389249,폐기물처리업체
10915,㈜남강엠앤테크,경기도 용인시 처인구 이동읍 서리로 185,37.195412,127.16996,폐기물처리업체
10916,하늘유통,경기도 용인시 처인구 백령로 34-8,37.263883,127.193177,폐기물처리업체

In [14]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10917 entries, 0 to 10916
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   소재지명    10917 non-null  object
 1   도로명     10917 non-null  object
 2   위도      10917 non-null  object
 3   경도      10917 non-null  object
 4   시설구분    10917 non-null  object
dtypes: object(5)
memory usage: 426.6+ KB

In [18]:
for i in range(len(df_all)):
    if (df_all.loc[i, '시설구분'] == '숙박업소') | (df_all.loc[i, '시설구분']  == '아파트주차장') | (df_all.loc[i,'시설구분'] == '관공서'):
        df_all['score'][i]  = 4
    elif (df_all.loc[i,'시설구분'] == '골프장') | (df_all.loc[i,'시설구분'] == '시장및마트') | (df_all.loc[i,'시설구분']== '대규모점포') | (df_all.loc[i,'시설구분']  == '응급의료기관'):
        df_all['score'][i]  = 3
    elif (df_all.loc[i,'시설구분'] == '영화상영관') | (df_all.loc[i,'시설구분'] == '공연장') | (df_all.loc[i,'시설구분'] == '박물관및미술관'):
        df_all['score'][i] = 2
    elif (df_all.loc[i,'시설구분'] == '음식점') | (df_all.loc[i,'시설구분'] == '의원') | (df_all.loc[i,'시설구분'] == '일반음식점'):
        df_all['score'][i] = 1
    else:
        df_all['score'][i] = 0
df_all

C:\Users\admin\AppData\Local\Temp\ipykernel_6188\3065463176.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_all['score'][i]  = 3
C:\Users\admin\AppData\Local\Temp\ipykernel_6188\3065463176.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_all['score'][i] = 2
C:\Users\admin\AppData\Local\Temp\ipykernel_6188\3065463176.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_all['score'][i] = 0
C:\Users\admin\AppData\Local\Temp\ipykernel_6188\3065463176.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_all['score'][i]  = 4
C:\Users\admin\AppData\Local\Temp\ipykernel_6188\3065463176.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_all['score'][i] = 1

,소재지명,도로명,위도,경도,시설구분,score
0,플라자(한화호텔앤드리조트㈜),경기도 용인시 처인구 남사면 봉무로 153번길 79,37.129816,127.148139,골프장,3
1,골드(기흥관광개발),경기도 용인시 기흥구 기흥단지로 398,37.217948,127.136339,골프장,3
2,태광(태광관광개발),경기도 용인시 기흥구 흥덕4로 77,37.278537,127.089073,골프장,3
3,태광대중(태광관광개발),경기도 용인시 기흥구 흥덕4로 77,37.278537,127.089073,골프장,3
4,한원(한원),경기도 용인시 처인구 남사면 전나무골길 2번길 94,37.153984,127.125162,골프장,3
...,...,...,...,...,...,...
10912,백옥영농조합,경기도 용인시 처인구 백암면 박곡로216번길 33,37.175227,127.401301,폐기물처리업체,0
10913,㈜케이블테크,경기도 용인시 처인구 남사면 각궁로 126,37.10104,127.154195,폐기물처리업체,0
10914,주식회사 신광상사,경기도 용인시 처인구 백암면 죽양대로 870-4,37.143541,127.389249,폐기물처리업체,0
10915,㈜남강엠앤테크,경기도 용인시 처인구 이동읍 서리로 185,37.195412,127.16996,폐기물처리업체,0
10916,하늘유통,경기도 용인시 처인구 백령로 34-8,37.263883,127.193177,폐기물처리업체,0