In [19]:
import pandas as pd

In [49]:
best = pd.read_csv('data/best_score.csv', index_col=0)
best.head()

    cell_id   cell_xcrd  cell_ycrd  overlap  person_cnt  best_score
0  86503006  127.165240  37.284084        3     255.975           5
1  86374994  127.160760  37.275060        2     174.924           5
2  83511270  127.059555  37.318443        3     162.099           5
3  85047108  127.113884  37.288887        1     156.700           5
4  84471258  127.093300  37.340195        3     150.741           5

# Best 5Ï†ê

In [50]:
best_5 = best[best['best_score'] == 5]
best_5.head()

    cell_id   cell_xcrd  cell_ycrd  overlap  person_cnt  best_score
0  86503006  127.165240  37.284084        3     255.975           5
1  86374994  127.160760  37.275060        2     174.924           5
2  83511270  127.059555  37.318443        3     162.099           5
3  85047108  127.113884  37.288887        1     156.700           5
4  84471258  127.093300  37.340195        3     150.741           5

In [51]:
best_5 = best_5[['cell_id', 'cell_ycrd', 'cell_xcrd']]
best_5.head()

    cell_id  cell_ycrd   cell_xcrd
0  86503006  37.284084  127.165240
1  86374994  37.275060  127.160760
2  83511270  37.318443  127.059555
3  85047108  37.288887  127.113884
4  84471258  37.340195  127.093300

In [52]:
best_5_dict = best_5.set_index(['cell_id']).T.to_dict('list')
best_5_dict

{86503006: [37.284084, 127.16524],
 86374994: [37.27506, 127.16076],
 83511270: [37.318443, 127.059555],
 85047108: [37.288887, 127.113884],
 84471258: [37.340195, 127.0933],
 83943044: [37.22881, 127.075294],
 84567237: [37.333447, 127.09672],
 85159177: [37.32315, 127.11765],
 84087216: [37.310402, 127.07992],
 83895245: [37.31804, 127.073105],
 85111182: [37.324047, 127.11596],
 90902570: [37.211857, 127.32052],
 84311190: [37.305023, 127.087845],
 89910687: [37.236588, 127.285515],
 85159024: [37.254196, 127.118004],
 83895264: [37.326603, 127.07305],
 83895244: [37.31759, 127.073105],
 85191015: [37.251045, 127.11915],
 87942919: [37.28557, 127.215996],
 85943027: [37.277718, 127.14552],
 86582917: [37.246235, 127.16822],
 87286857: [37.23909, 127.193054],
 93254247: [37.13263, 127.40346],
 86295015: [37.28226, 127.15791],
 84663249: [37.34157, 127.10007],
 90694539: [37.192017, 127.31324],
 84583245: [37.337505, 127.09726],
 92854286: [37.138927, 127.38937],
 87478830: [37.232346, 127.199844],
 90742560: [37.202835, 127.3149],
 85319106: [37.295677, 127.123436],
 84679225: [37.331207, 127.100685],
 84119206: [37.3068, 127.08106],
 86039033: [37.283134, 127.14888],
 85575168: [37.33086, 127.13229],
 83527278: [37.3225, 127.0601],
 86614899: [37.239025, 127.16938],
 84023228: [37.314, 127.07764],
 86742894: [37.24039, 127.17388],
 90262644: [37.227146, 127.297935],
 84215205: [37.309067, 127.084435],
 84103226: [37.31536, 127.08045],
 84631234: [37.333904, 127.098976],
 86231005: [37.275944, 127.155685],
 84967166: [37.312763, 127.11094],
 84007226: [37.312645, 127.07708],
 84855100: [37.27985, 127.10716],
 83735216: [37.30044, 127.06756],
 83895219: [37.306324, 127.073166],
 86278991: [37.270992, 127.157394],
 84679091: [37.270813, 127.101006],
 86007003: [37.26871, 127.14782],
 83287316: [37.332832, 127.05157],
 87958884: [37.27025, 127.21661],
 84359252: [37.334324, 127.08938],
 83671250: [37.313957, 127.06522],
 85383095: [37.29253, 127.12571],
 87718729: [37.193607, 127.20845],
 83623269: [37.32116, 127.06349],
 85239096: [37.288906, 127.12065],
 83591253: [37.313046, 127.06241],
 83703250: [37.31486, 127.066345],
 84567214: [37.323082, 127.09678],
 90934480: [37.1722, 127.32174],
 85031189: [37.32494, 127.11313],
 84071038: [37.22973, 127.0798],
 86279010: [37.279556, 127.15736],
 91014535: [37.199245, 127.32449],
 84023198: [37.30048, 127.07771],
 84343258: [37.336575, 127.0888],
 83895153: [37.276577, 127.07333],
 87142750: [37.186794, 127.188194],
 85479055: [37.277218, 127.129166],
 84551216: [37.32353, 127.09621],
 88006801: [37.234196, 127.21844],
 84503096: [37.26809, 127.09481],
 84471195: [37.311802, 127.09345],
 85847046: [37.283566, 127.14211],
 84375196: [37.309536, 127.09008],
 83927060: [37.23557, 127.07469],
 84967187: [37.322227, 127.110886],
 84967125: [37.294285, 127.11103],
 85223097: [37.288906, 127.12009],
 87222855: [37.236378, 127.19081],
 85894736: [37.145206, 127.144455],
 86183052: [37.29577, 127.1539],
 84487253: [37.338394, 127.09387],
 84375245: [37.33162, 127.08996],
 84375197: [37.30999, 127.09007],
 84983131: [37.29744, 127.11158],
 84983120: [37.292484, 127.1116],
 84839108: [37.283, 127.106575],
 84055250: [37.32482, 127.078705],
 87606733: [37.192245, 127.20451],
 85431060: [37.27811, 127.12747],
 84599173: [37.305508, 127.098],
 84151234: [37.320328, 127.082115],
 89334699: [37.225735, 127.26525],
 84967202: [37.328987, 127.110855],
 85431116: [37.303352, 127.12735],
 89910685: [37.235687, 127.285515],
 83975238: [37.31715, 127.07593],
 83991226: [37.312195, 127.07652],
 82999397: [37.361187, 127.04124],
 85079026: [37.252834, 127.1152],
 83879240: [37.315334, 127.072556],
 88103055: [37.351383, 127.22139],
 88374801: [37.24459, 127.23137],
 87814875: [37.262123, 127.21157],
 85079200: [37.331253, 127.11479],
 85015175: [37.318176, 127.1126],
 84039254: [37.32617, 127.07813],
 88902964: [37.33297, 127.24968],
 84391184: [37.30458, 127.09067],
 84183215: [37.312668, 127.08329],
 84423221: [37.322163, 127.091705],
 85911051: [37.28763, 127.14435],
 90758544: [37.196075, 127.31549],
 85063175: [37.319534, 127.11429],
 84487218: [37.32262, 127.093956],
 87430903: [37.26389, 127.19803],
 84471251: [37.33704, 127.093315],
 84887114: [37.287064, 127.10825],
 86886851: [37.225082, 127.17902],
 88726964: [37.327995, 127.24349],
 87974810: [37.237347, 127.2173],
 83991199: [37.300026, 127.07659],
 85207013: [37.250595, 127.11971],
 86550918: [37.24578, 127.16709],
 88262855: [37.265766, 127.22735],
 85527053: [37.27767, 127.13086],
 85926978: [37.25518, 127.145065],
 87478837: [37.2355, 127.19984],
 83911060: [37.235115, 127.074135],
 85191008: [37.24789, 127.11916],
 85047204: [37.332153, 127.11366],
 87654896: [37.267067, 127.20591],
 87238863: [37.240437, 127.19136],
 84967140: [37.301044, 127.111],
 83671283: [37.328827, 127.06514],
 87206866: [37.240887, 127.19023],
 86167044: [37.29171, 127.15335],
 84999196: [37.327187, 127.11199],
 84423271: [37.344696, 127.09158],
 86215008: [37.276844, 127.15511],
 84231187: [37.301407, 127.085045],
 88518823: [37.258575, 127.2364],
 83847247: [37.317585, 127.07141],
 83815252: [37.31893, 127.070274],
 88326820: [37.251797, 127.22965],
 84151145: [37.280216, 127.08234],
 83911223: [37.30858, 127.07372],
 85207012: [37.250145, 127.11972],
 85575173: [37.33311, 127.13228],
 85959035: [37.281776, 127.146065],
 88086900: [37.281075, 127.221085],
 84663054: [37.253685, 127.10053],
 84039211: [37.306793, 127.07825],
 87542827: [37.232803, 127.2021],
 86695074: [37.32016, 127.171844],
 84455201: [37.314053, 127.09287],
 87462831: [37.232346, 127.19928],
 85159100: [37.28845, 127.11783],
 84935148: [37.303745, 127.109856],
 84567230: [37.33029, 127.09674],
 84343100: [37.265366, 127.08919],
 86823112: [37.340904, 127.17627],
 86006994: [37.264652, 127.14784],
 89718672: [37.224407, 127.278786],
 83735275: [37.327034, 127.067406],
 84119198: [37.303196, 127.081085],
 84087210: [37.307697, 127.07993],
 84247249: [37.329803, 127.08545],
 85399191: [37.336246, 127.12605],
 85207177: [37.32451, 127.11934],
 84183084: [37.253628, 127.08362],
 84375276: [37.345592, 127.08988],
 85287193: [37.33398, 127.122116],
 84775228: [37.335274, 127.10405],
 84471231: [37.328026, 127.09336],
 85607031: [37.27002, 127.13371],
 83879154: [37.276577, 127.07277],
 84999101: [37.284374, 127.11221],
 88982990: [37.346947, 127.25246],
 88182895: [37.281532, 127.22447],
 85447125: [37.30786, 127.12789],
 86502923: [37.246677, 127.1654],
 84183221: [37.315372, 127.083275],
 87958868: [37.263035, 127.216644],
 84103200: [37.303646, 127.08052],
 84711225: [37.33211, 127.10181],
 86951083: [37.33145, 127.180824],
 84887106: [37.28346, 127.10827],
 87542826: [37.232353, 127.2021],
 84103209: [37.3077, 127.0805],
 84215207: [37.309967, 127.084435],
 84951206: [37.330338, 127.11028],
 87478829: [37.231895, 127.19985],
 87942884: [37.269794, 127.21605],
 87958791: [37.228333, 127.216774],
 84327207: [37.313137, 127.08836],
 84743006: [37.234318, 127.10345],
 84855222: [37.334835, 127.10687],
 87206855: [37.235928, 127.19025],
 85718999: [37.258762, 127.13772],
 84823076: [37.268127, 127.106094],
 83943267: [37.329315, 127.07473],
 84167215: [37.312218, 127.082726],
 84871088: [37.274895, 127.10775],
 84551241: [37.334797, 127.096146],
 85367116: [37.30154, 127.1251],
 84007199: [37.30048, 127.07715],
 84391014: [37.227966, 127.09108],
 85958951: [37.243916, 127.14625],
 84055205: [37.30454, 127.07882],
 84855107: [37.283005, 127.10714],
 86310999: [37.2755, 127.1585],
 88982899: [37.30593, 127.252594],
 90262653: [37.2312, 127.29793],
 84375275: [37.345142, 127.08988],
 86039025: [37.27953, 127.148895],
 83671308: [37.340096, 127.06507],
 91062516: [37.192036, 127.3262],
 88950980: [37.341534, 127.25134],
 84695240: [37.33842, 127.10121],
 87942820: [37.24095, 127.21616],
 86103057: [37.29576, 127.15108],
 84487195: [37.312256, 127.09401],
 85767027: [37.27274, 127.13934],
 83783157: [37.27521, 127.0694],
 87462839: [37.23595, 127.19927],
 85287179: [37.32767, 127.12215],
 84375200: [37.31134, 127.090065],
 83799202: [37.295944, 127.06984],
 84951117: [37.290226, 127.11049],
 86550916: [37.244877, 127.1671],
 83975148: [37.27659, 127.07616],
 85063186: [37.324493, 127.114265],
 85255193: [37.333076, 127.120995],
 87318849: [37.23639, 127.19419],
 84407231: [37.326218, 127.09112],
 86726705: [37.154755, 127.17369],
 84823227: [37.33618, 127.105736],
 84535095: [37.268543, 127.09594],
 84039058: [37.237835, 127.07863],
 83591256: [37.314396, 127.0624],
 85527100: [37.298855, 127.13075],
 85447058: [37.277664, 127.12804],
 88854675: [37.201363, 127.24843],
 85494991: [37.248825, 127.129875],
 85750995: [37.257866, 127.13885],
 85399093: [37.29208, 127.126274],
 87798816: [37.235077, 127.21111],
 84855223: [37.335285, 127.10687],
 85239174: [37.324062, 127.120476],
 87942917: [37.284668, 127.215996],
 88918972: [37.337025, 127.25023],
 87942823: [37.242302, 127.216156],
 84967205: [37.33034, 127.11085],
 85015205: [37.331696, 127.11253],
 86854807: [37.204346, 127.177986],
 84071246: [37.32347, 127.07928],
 85079174: [37.319534, 127.11485],
 87702830: [37.238674, 127.20771],
 87046793: [37.20346, 127.184746],
 87910798: [37.23013, 127.21507],
 83783205: [37.296844, 127.069275],
 83527316: [37.339626, 127.06],
 84567254: [37.34111, 127.09668],
 84903091: [37.27715, 127.108864],
 84071202: [37.303642, 127.07939],
 84583204: [37.319027, 127.09736],
 87494833: [37.23415, 127.2004],
 84823224: [37.33483, 127.10574],
 87398838: [37.233692, 127.19702],
 84871098: [37.2794, 127.10773],
 87814868: [37.25897, 127.211586],
 84263226: [37.31989, 127.08607],
 86583005: [37.285896, 127.168045],
 83943145: [37.27433, 127.07504],
 86630714: [37.156097, 127.1703],
 83735272: [37.325684, 127.06741],
 83799275: [37.328846, 127.06966],
 87414849: [37.2391, 127.19756],
 86262979: [37.26513, 127.15686],
 86726716: [37.159714, 127.17367],
 86039026: [37.27998, 127.148895],
 91142614: [37.23846, 127.32891],
 85975064: [37.295296, 127.14657],
 83735264: [37.322075, 127.06744],
 84663252: [37.342922, 127.10006],
 86007025: [37.278625, 127.14777],
 85510782: [37.155083, 127.13089],
 88230827: [37.252243, 127.226265],
 86791114: [37.3409, 127.17514],
 84503219: [37.323524, 127.09451],
 87830892: [37.270237, 127.212105],
 84103198: [37.302742, 127.08052],
 83895235: [37.313534, 127.07313],
 86951110: [37.34362, 127.18078],
 88182881: [37.275223, 127.224495],
 83719261: [37.32027, 127.06688],
 86886744: [37.176857, 127.17923],
 83927194: [37.29596, 127.074356],
 86327011: [37.28136, 127.15904],
 87430837: [37.234146, 127.19815],
 85223189: [37.330368, 127.11988],
 85222958: [37.22626, 127.1204],
 84903090: [37.2767, 127.108864],
 86518881: [37.2282, 127.166046],
 85671024: [37.268673, 127.13598],
 85367006: [37.251965, 127.12534],
 87478890: [37.259388, 127.19974],
 83655215: [37.29773, 127.06476],
 83751250: [37.31622, 127.06803]}

In [53]:
office = pd.read_csv('res/Í¥ÄÍ≥µÏÑúÌòÑÌô©.csv', index_col=0)
office.head()

   ÏÜåÏû¨ÏßÄÎ™Ö                       ÎèÑÎ°úÎ™Ö         ÏúÑÎèÑ          Í≤ΩÎèÑ ÏãúÏÑ§Íµ¨Î∂Ñ
0  Ïö©Ïù∏ÏãúÏ≤≠     Í≤ΩÍ∏∞ÎèÑ Ïö©Ïù∏Ïãú Ï≤òÏù∏Íµ¨ Ï§ëÎ∂ÄÎåÄÎ°ú 1199  37.240608  127.177294  Í¥ÄÍ≥µÏÑú
1  Ï≤òÏù∏Íµ¨Ï≤≠        Í≤ΩÍ∏∞ÎèÑ Ïö©Ïù∏Ïãú Ï≤òÏù∏Íµ¨ Í∏àÎ†πÎ°ú 50  37.234474  127.201408  Í¥ÄÍ≥µÏÑú
2   Ìè¨Í≥°Ïùç   Í≤ΩÍ∏∞ÎèÑ Ïö©Ïù∏Ïãú Ï≤òÏù∏Íµ¨ Ìè¨Í≥°Ïùç Ìè¨Í≥°Î°ú 258  37.277715  127.230957  Í¥ÄÍ≥µÏÑú
3   Î™®ÌòÑÏùç  Í≤ΩÍ∏∞ÎèÑ Ïö©Ïù∏Ïãú Ï≤òÏù∏Íµ¨ Î™®ÌòÑÎ©¥ ÎèÖÏ†êÎ°ú 31-6  37.329479  127.242276  Í¥ÄÍ≥µÏÑú
4   ÎÇ®ÏÇ¨Î©¥    Í≤ΩÍ∏∞ÎèÑ Ïö©Ïù∏Ïãú Ï≤òÏù∏Íµ¨ ÎÇ®ÏÇ¨Î©¥ ÎÇ¥Í∏∞Î°ú 22  37.115301  127.150214  Í¥ÄÍ≥µÏÑú

In [54]:
office = office[['ÏÜåÏû¨ÏßÄÎ™Ö', 'ÏúÑÎèÑ', 'Í≤ΩÎèÑ']]
office.head()

   ÏÜåÏû¨ÏßÄÎ™Ö         ÏúÑÎèÑ          Í≤ΩÎèÑ
0  Ïö©Ïù∏ÏãúÏ≤≠  37.240608  127.177294
1  Ï≤òÏù∏Íµ¨Ï≤≠  37.234474  127.201408
2   Ìè¨Í≥°Ïùç  37.277715  127.230957
3   Î™®ÌòÑÏùç  37.329479  127.242276
4   ÎÇ®ÏÇ¨Î©¥  37.115301  127.150214

In [55]:
office_dict = office.set_index(['ÏÜåÏû¨ÏßÄÎ™Ö']).T.to_dict('list')
office_dict

{'Ïö©Ïù∏ÏãúÏ≤≠': [37.240608, 127.1772935],
 'Ï≤òÏù∏Íµ¨Ï≤≠': [37.2344735, 127.2014077],
 'Ìè¨Í≥°Ïùç': [37.2777155, 127.2309574],
 'Î™®ÌòÑÏùç': [37.3294787, 127.2422761],
 'ÎÇ®ÏÇ¨Î©¥': [37.115301, 127.1502137],
 'Ïù¥ÎèôÏùç': [37.12746, 127.1893731],
 'ÏõêÏÇºÎ©¥': [37.1653644, 127.3103786],
 'Î∞±ÏïîÎ©¥': [37.1636946, 127.3753866],
 'ÏñëÏßÄÎ©¥': [37.2357405, 127.2801214],
 'Ï§ëÏïôÎèô': [37.2341249, 127.2051699],
 'Ïó≠ÏÇºÎèô': [37.2345179, 127.1879177],
 'Ïú†Î¶ºÎèô': [37.2524204, 127.2117187],
 'ÎèôÎ∂ÄÎèô': [37.2327418, 127.2191418],
 'Í∏∞Ìù•Íµ¨Ï≤≠': [37.2802242, 127.1151398],
 'Ïã†Í∞àÎèô': [37.2725093, 127.1070081],
 'ÏòÅÎçïÎèô': [37.2718661, 127.0737664],
 'Íµ¨Í∞àÎèô': [37.2724176, 127.1275789],
 'ÏÉÅÍ∞àÎèô': [37.2665434, 127.1076299],
 'Í∏∞Ìù•Îèô': [37.2322301, 127.1143893],
 'ÏÑúÎÜçÎèô': [37.2403129, 127.0755947],
 'Íµ¨ÏÑ±Îèô': [37.2965012, 127.1189634],
 'ÎßàÎ∂ÅÎèô': [37.3022246, 127.1173194],
 'ÎèôÎ∞±Îèô': [37.2705385, 127.1563635],
 'ÏÉÅÌïòÎèô': [37.2702308, 127.1380528],
 'Î≥¥Ï†ïÎèô': [37.3266759, 127.1253051],
 'ÏàòÏßÄÍµ¨Ï≤≠': [37.3241541, 127.0932899],
 'ÌíçÎçïÏ≤ú1Îèô': [37.3278713, 127.0950572],
 'ÌíçÎçïÏ≤ú2Îèô': [37.3193826, 127.0886558],
 'Ïã†Î¥âÎèô': [37.3206332, 127.0836188],
 'Ï£ΩÏ†Ñ1Îèô': [37.3309473, 127.1138276],
 'Ï£ΩÏ†Ñ2Îèô': [37.3324967, 127.1128141],
 'ÎèôÏ≤úÎèô': [37.341641, 127.0989977],
 'ÏÉÅÌòÑ1Îèô': [37.3045954, 127.0811366],
 'ÏÉÅÌòÑ2Îèô': [37.3121418, 127.0872845],
 'ÏÑ±Î≥µÎèô': [37.3164107, 127.0689606]}

In [56]:
! pip install haversine

Requirement already satisfied: haversine in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (2.7.0)

WARNING: Ignoring invalid distribution -lotly (c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages)
WARNING: Ignoring invalid distribution -lotly (c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages)
WARNING: Ignoring invalid distribution -lotly (c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages)
WARNING: Ignoring invalid distribution -lotly (c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages)
WARNING: Ignoring invalid distribution -lotly (c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages)
WARNING: Ignoring invalid distribution -lotly (c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages)

In [57]:
from haversine import haversine

In [58]:
df_all = pd.DataFrame(columns=["best_name", "office_name", "Í±∞Î¶¨Ï∞®Ïù¥", "score"])

for i in range(0, len(best_5_dict)) :
    best_nm = list(best_5_dict.keys())[i]
    best_xy = list(best_5_dict.items())[i][1]

    for j in range(0, len(office_dict)) :
        office_nm = list(office_dict.keys())[j]
        office_xy = list(office_dict.items())[j][1]

        ## ÏµúÏ¢Ö Í±∞Î¶¨ Í≥ÑÏÇ∞ Í≤∞Í≥ºÍ∞í
        result = haversine(best_xy, office_xy, unit='m')

        score = 0
        if result <= 200:
            score = 5
        elif 200 < result <= 400:
            score = 4
        elif 400 < result <= 600:
            score = 3
        elif 600 < result <= 800:
            score = 2
        elif 800 < result <= 1000:
            score = 1
        df_all = pd.concat([df_all, 
                        pd.DataFrame({'best_name':[best_nm],'office_name':[office_nm], 'Í±∞Î¶¨Ï∞®Ïù¥':[result], 'score':[score]})], ignore_index=True)
df_all

      best_name office_name          Í±∞Î¶¨Ï∞®Ïù¥ score
0      86503006        Ïö©Ïù∏ÏãúÏ≤≠   4950.602954     0
1      86503006        Ï≤òÏù∏Íµ¨Ï≤≠   6377.826708     0
2      86503006         Ìè¨Í≥°Ïùç   5857.324404     0
3      86503006         Î™®ÌòÑÏùç   8479.498447     0
4      86503006         ÎÇ®ÏÇ¨Î©¥  18814.968734     0
...         ...         ...           ...   ...
11020  83751250        Ï£ΩÏ†Ñ2Îèô   4353.991475     0
11021  83751250         ÎèôÏ≤úÎèô   3935.415980     0
11022  83751250        ÏÉÅÌòÑ1Îèô   1736.216835     0
11023  83751250        ÏÉÅÌòÑ2Îèô   1762.141051     0
11024  83751250         ÏÑ±Î≥µÎèô     84.984245     5

[11025 rows x 4 columns]

In [63]:
df_all_5 = df_all.groupby('office_name')['score'].sum()
df_all_5 = df_all_5.reset_index()
df_all_5 = df_all_5.rename(columns = {'score' : '5_score'})
df_all_5

   office_name 5_score
0          Íµ¨Í∞àÎèô      13
1          Íµ¨ÏÑ±Îèô      19
2         Í∏∞Ìù•Íµ¨Ï≤≠      20
3          Í∏∞Ìù•Îèô       2
4          ÎÇ®ÏÇ¨Î©¥       0
5          ÎèôÎ∞±Îèô      19
6          ÎèôÎ∂ÄÎèô      17
7          ÎèôÏ≤úÎèô      39
8          ÎßàÎ∂ÅÎèô      11
9          Î™®ÌòÑÏùç       7
10         Î∞±ÏïîÎ©¥       0
11         Î≥¥Ï†ïÎèô      20
12         ÏÉÅÍ∞àÎèô       7
13         ÏÉÅÌïòÎèô      13
14        ÏÉÅÌòÑ1Îèô      71
15        ÏÉÅÌòÑ2Îèô      59
16         ÏÑúÎÜçÎèô      10
17         ÏÑ±Î≥µÎèô      52
18        ÏàòÏßÄÍµ¨Ï≤≠      37
19         Ïã†Í∞àÎèô      19
20         Ïã†Î¥âÎèô      33
21         ÏñëÏßÄÎ©¥       6
22         Ïó≠ÏÇºÎèô      20
23         ÏòÅÎçïÎèô      16
24        Ïö©Ïù∏ÏãúÏ≤≠       6
25         ÏõêÏÇºÎ©¥       0
26         Ïú†Î¶ºÎèô       2
27         Ïù¥ÎèôÏùç       0
28        Ï£ΩÏ†Ñ1Îèô      53
29        Ï£ΩÏ†Ñ2Îèô      48
30         Ï§ëÏïôÎèô      38
31        Ï≤òÏù∏Íµ¨Ï≤≠      52
32         Ìè¨Í≥°Ïùç       5
33       ÌíçÎçïÏ≤ú1Îèô      41
34       ÌíçÎçïÏ≤ú2Îèô      34

# Best 4Ï†ê

In [60]:
best_4 = best[best['best_score'] == 4]
best_4.head()

      cell_id   cell_xcrd  cell_ycrd  overlap  person_cnt  best_score
315  85094952  127.115920  37.219936        3      70.010           4
316  86694892  127.172200  37.238132        3      70.010           4
317  85895006  127.143880  37.266895        3      69.965           4
318  86278976  127.157425  37.264233        3      69.940           4
319  90086602  127.291800  37.203247        2      69.808           4

In [61]:
best_4 = best_4[['cell_id', 'cell_ycrd', 'cell_xcrd']]
best_4.head()

      cell_id  cell_ycrd   cell_xcrd
315  85094952  37.219936  127.115920
316  86694892  37.238132  127.172200
317  85895006  37.266895  127.143880
318  86278976  37.264233  127.157425
319  90086602  37.203247  127.291800

In [62]:
best_4_dict = best_4.set_index(['cell_id']).T.to_dict('list')
best_4_dict

{85094952: [37.219936, 127.11592],
 86694892: [37.238132, 127.1722],
 85895006: [37.266895, 127.14388],
 86278976: [37.264233, 127.157425],
 90086602: [37.203247, 127.2918],
 84823064: [37.26272, 127.10612],
 85063198: [37.3299, 127.114235],
 85799002: [37.26238, 127.14052],
 87654735: [37.194504, 127.20619],
 87366633: [37.140392, 127.196266],
 84231199: [37.306816, 127.085014],
 89830690: [37.235683, 127.2827],
 85079135: [37.30196, 127.114944],
 84839029: [37.2474, 127.106766],
 86630716: [37.157, 127.1703],
 86199043: [37.292168, 127.15448],
 88630884: [37.28923, 127.240234],
 87958894: [37.274754, 127.2166],
 84375215: [37.3181, 127.090034],
 84087042: [37.231983, 127.08035],
 92326377: [37.16505, 127.37075],
 83767089: [37.24411, 127.06901],
 83911145: [37.273426, 127.07392],
 85399096: [37.29343, 127.12627],
 87702789: [37.220196, 127.20779],
 89014710: [37.221653, 127.25399],
 86279020: [37.28406, 127.15734],
 91126510: [37.19114, 127.32845],
 87958812: [37.237797, 127.216736],
 85750998: [37.259216, 127.13884],
 85175115: [37.295662, 127.11836],
 85303102: [37.293423, 127.12289],
 84215201: [37.307262, 127.08445],
 84343074: [37.253647, 127.08926],
 90646623: [37.22852, 127.31146],
 86551002: [37.283638, 127.16693],
 84983035: [37.254173, 127.1118],
 85415122: [37.305603, 127.12677],
 85015021: [37.24877, 127.11296],
 84935093: [37.278957, 127.109985],
 82807429: [37.370174, 127.03441],
 84663218: [37.3276, 127.100136],
 88966936: [37.322155, 127.251976],
 88918960: [37.331615, 127.25025],
 88982970: [37.337933, 127.25249],
 85063106: [37.288437, 127.11445],
 85687023: [37.268677, 127.13654],
 85095032: [37.25599, 127.11574],
 87622733: [37.1927, 127.20507],
 85062958: [37.221733, 127.114784],
 84887197: [37.32447, 127.108055],
 87926859: [37.258076, 127.21553],
 84167228: [37.318073, 127.082695],
 85207175: [37.32361, 127.11935],
 83767275: [37.327938, 127.068535],
 87270852: [37.236385, 127.192505],
 83991040: [37.228367, 127.07699],
 84855159: [37.30644, 127.10702],
 83911268: [37.328857, 127.07361],
 86199025: [37.284054, 127.15452],
 87382931: [37.275154, 127.1963],
 84983034: [37.253723, 127.11181],
 84263201: [37.30862, 127.086136],
 84855200: [37.324917, 127.106926],
 84455262: [37.341545, 127.09273],
 85910623: [37.09473, 127.14525],
 83751246: [37.314415, 127.06805],
 85719036: [37.27544, 127.137634],
 85079030: [37.254635, 127.11518],
 87750864: [37.255356, 127.20934],
 86167047: [37.293064, 127.15335],
 84327191: [37.305927, 127.0884],
 87430833: [37.23234, 127.19816],
 84439233: [37.328022, 127.09223],
 87814804: [37.23012, 127.21169],
 83991227: [37.312645, 127.076515],
 86694717: [37.15926, 127.17255],
 85254993: [37.24294, 127.121445],
 85991029: [37.279976, 127.1472],
 89350946: [37.33751, 127.26547],
 84903050: [37.25867, 127.10896],
 85639025: [37.26822, 127.13485],
 87222856: [37.23683, 127.19081],
 84647247: [37.340218, 127.09951],
 86199030: [37.28631, 127.15451],
 88998982: [37.343792, 127.25303],
 84583242: [37.33615, 127.09727],
 84391183: [37.30413, 127.09067],
 87366841: [37.23414, 127.19589],
 84695232: [37.334816, 127.10123],
 86774750: [37.176395, 127.175285],
 90614641: [37.23573, 127.31032],
 84135185: [37.29779, 127.08168],
 87462837: [37.23505, 127.19927],
 87894591: [37.136383, 127.21487],
 85495084: [37.290737, 127.12967],
 85063027: [37.25283, 127.11463],
 83847084: [37.24412, 127.07183],
 88822738: [37.22885, 127.24721],
 83671257: [37.317112, 127.06521],
 87510831: [37.2337, 127.200966],
 84727240: [37.339325, 127.10233],
 84583254: [37.34156, 127.097244],
 89142982: [37.34786, 127.2581],
 83543261: [37.315292, 127.06071],
 84791093: [37.274883, 127.10493],
 92838321: [37.15425, 127.38879],
 87414850: [37.23955, 127.19756],
 85159175: [37.32225, 127.11766],
 84903097: [37.279854, 127.10885],
 84279192: [37.30502, 127.086716],
 87846548: [37.115646, 127.21325],
 84903198: [37.325375, 127.10861],
 85687022: [37.268227, 127.13654],
 83815087: [37.244568, 127.0707],
 90806640: [37.2407, 127.31707],
 85143176: [37.322247, 127.117096],
 86550919: [37.24623, 127.16709],
 83831271: [37.327946, 127.070786],
 86695118: [37.33999, 127.17176],
 85783111: [37.31105, 127.139725],
 88470912: [37.29733, 127.234566],
 84983204: [37.33034, 127.11141],
 90646632: [37.23258, 127.311455],
 85527123: [37.30922, 127.13071],
 86375020: [37.286774, 127.16071],
 85399185: [37.33354, 127.12607],
 84887199: [37.32537, 127.10805],
 85079080: [37.277172, 127.11507],
 87686894: [37.267067, 127.20704],
 84455197: [37.312252, 127.09288],
 84935057: [37.262733, 127.11007],
 86151063: [37.299824, 127.152756],
 87542844: [37.240463, 127.20207],
 84375256: [37.33658, 127.08993],
 84663214: [37.325798, 127.10015],
 84167203: [37.30681, 127.082756],
 86279008: [37.278652, 127.157364],
 87958920: [37.286472, 127.21655],
 86167033: [37.286755, 127.15337],
 87063100: [37.342278, 127.18473],
 84967116: [37.29023, 127.11105],
 85143020: [37.25194, 127.117455],
 84087208: [37.306797, 127.07993],
 86918876: [37.23725, 127.1801],
 83767270: [37.325687, 127.06854],
 84823075: [37.267677, 127.106094],
 84519070: [37.256824, 127.095436],
 83767070: [37.23555, 127.06906],
 84951210: [37.33214, 127.110275],
 84855097: [37.278496, 127.10716],
 85175183: [37.326305, 127.1182],
 83943045: [37.22926, 127.075294],
 83735085: [37.2414, 127.067894],
 87366848: [37.237293, 127.195885],
 84391232: [37.326214, 127.09055],
 84439199: [37.3127, 127.092316],
 84951168: [37.313213, 127.110374],
 87494835: [37.23505, 127.2004],
 87974701: [37.18822, 127.21748],
 84871159: [37.306892, 127.10758],
 84550987: [37.22032, 127.09676],
 93238248: [37.13263, 127.40289],
 84935209: [37.331238, 127.10971],
 83831279: [37.331554, 127.07077],
 87094856: [37.23321, 127.18632],
 86390987: [37.272354, 127.16134],
 84519225: [37.32668, 127.09506],
 85991010: [37.27141, 127.14725],
 83991236: [37.3167, 127.07649],
 86167009: [37.275936, 127.15343],
 84951116: [37.289776, 127.11049],
 85750997: [37.258766, 127.13885],
 84423117: [37.27529, 127.09196],
 84183024: [37.226585, 127.08376],
 87430845: [37.23775, 127.198135],
 85927032: [37.27952, 127.14495],
 84967208: [37.33169, 127.11084],
 88134881: [37.27387, 127.22281],
 85063194: [37.3281, 127.11424],
 86935109: [37.342716, 127.180214],
 85079184: [37.324043, 127.11483],
 84935026: [37.24876, 127.11014],
 87334849: [37.23684, 127.194756],
 84967085: [37.276257, 127.11112],
 85335158: [37.319565, 127.12388],
 85239093: [37.287556, 127.12066],
 89686697: [37.23477, 127.277626],
 89014752: [37.240585, 127.25393],
 84375187: [37.30548, 127.0901],
 86375125: [37.3341, 127.1605],
 88726933: [37.314026, 127.24354],
 84999142: [37.302853, 127.112114],
 87782875: [37.26122, 127.21045],
 88006873: [37.266644, 127.21832],
 84487226: [37.326225, 127.09394],
 87222833: [37.226463, 127.19085],
 84839089: [37.27444, 127.10662],
 83863073: [37.239616, 127.07242],
 84183023: [37.226135, 127.08376],
 85271071: [37.278545, 127.12183],
 84823047: [37.25506, 127.10616],
 84999094: [37.28122, 127.11223],
 85495056: [37.27812, 127.12973],
 83767258: [37.32028, 127.06857],
 88982977: [37.341087, 127.25247],
 87367072: [37.33825, 127.19547],
 84887088: [37.275345, 127.10831],
 86855111: [37.341354, 127.1774],
 84311215: [37.316288, 127.08778],
 83927227: [37.310833, 127.07427],
 85367096: [37.292526, 127.125145],
 86439004: [37.281372, 127.16299],
 84103141: [37.277054, 127.080666],
 84183121: [37.270306, 127.08353],
 85959048: [37.287632, 127.14604],
 84279231: [37.322594, 127.086624],
 85686798: [37.16727, 127.13703],
 85207061: [37.27223, 127.119606],
 83431312: [37.335106, 127.05664],
 83783259: [37.321182, 127.06914],
 84471085: [37.262226, 127.09372],
 84855105: [37.282104, 127.10715],
 89878675: [37.230278, 127.2844],
 84807047: [37.254604, 127.1056],
 85767042: [37.279503, 127.13931],
 87254853: [37.23638, 127.19194],
 87478819: [37.22739, 127.19987],
 83799243: [37.314423, 127.06974],
 84295260: [37.336117, 127.08711],
 84391270: [37.34334, 127.09046],
 84935107: [37.285267, 127.109955],
 84871060: [37.262276, 127.10781],
 85671029: [37.270927, 127.13596],
 84455203: [37.314957, 127.09287],
 83927145: [37.273876, 127.07448],
 84551250: [37.338852, 127.09613],
 84455247: [37.334785, 127.092766],
 88390800: [37.24459, 127.23193],
 85719018: [37.267326, 127.13767],
 85079198: [37.330353, 127.1148],
 85127201: [37.33306, 127.11648],
 84935201: [37.327633, 127.10973],
 85783026: [37.272743, 127.13991],
 84295196: [37.307274, 127.087265],
 83591254: [37.313496, 127.06241],
 85303110: [37.297028, 127.12286],
 85223190: [37.33082, 127.11987],
 85719164: [37.333126, 127.13736],
 83719263: [37.321175, 127.06688],
 84983181: [37.319977, 127.111465],
 84567245: [37.33705, 127.0967],
 85239121: [37.300175, 127.12059],
 84263218: [37.316284, 127.08609],
 84039152: [37.2802, 127.07839],
 88055002: [37.32614, 127.21979],
 86167019: [37.280445, 127.153404],
 89750667: [37.223057, 127.279915],
 83975262: [37.327965, 127.07587],
 85783112: [37.3115, 127.139725],
 83815155: [37.275215, 127.070526],
 84679208: [37.323544, 127.10072],
 85559035: [37.270466, 127.13202],
 83847056: [37.231503, 127.0719],
 84823228: [37.33663, 127.105736],
 83927219: [37.307228, 127.074295],
 85111088: [37.28168, 127.11617],
 84807224: [37.334377, 127.10518],
 86726896: [37.24084, 127.17332],
 84135214: [37.31086, 127.081604],
 86134995: [37.268723, 127.15233],
 85862964: [37.247063, 127.142845],
 85399156: [37.320473, 127.12614],
 84231253: [37.331154, 127.08488],
 83991258: [37.326614, 127.07644],
 84183219: [37.314472, 127.08328],
 84375222: [37.321255, 127.09001],
 85479120: [37.30651, 127.12903],
 84886985: [37.228924, 127.10855],
 86838881: [37.237244, 127.17728],
 87990867: [37.26349, 127.217766],
 84455225: [37.32487, 127.09282],
 86534718: [37.15519, 127.16693],
 83895209: [37.301815, 127.0732],
 85479176: [37.33175, 127.1289],
 83719285: [37.33109, 127.06682],
 86550935: [37.25344, 127.16706],
 86215007: [37.276394, 127.15511],
 85127077: [37.277176, 127.11676],
 83783258: [37.320732, 127.06914],
 85159026: [37.255096, 127.118004],
 85654986: [37.251095, 127.1355],
 83975219: [37.308586, 127.07597],
 90710482: [37.16678, 127.313866],
 84119243: [37.32348, 127.08097],
 88918974: [37.33793, 127.25023],
 88966850: [37.283398, 127.2521],
 85015132: [37.298798, 127.1127],
 85031033: [37.25463, 127.113495],
 84887016: [37.242897, 127.108475],
 84119218: [37.31221, 127.08103],
 83879246: [37.31804, 127.07254],
 85591030: [37.269115, 127.133156],
 84231219: [37.31583, 127.08496],
 84407247: [37.333427, 127.09108],
 86150997: [37.270077, 127.15289],
 84599194: [37.314972, 127.097946],
 83879146: [37.27297, 127.07279],
 90550633: [37.230316, 127.308075],
 84535212: [37.321274, 127.09566],
 85383115: [37.301544, 127.12566],
 83767253: [37.318024, 127.06859],
 83719265: [37.322075, 127.06687],
 86167020: [37.280895, 127.153404],
 84999068: [37.2695, 127.11229]}

In [64]:
df_all = pd.DataFrame(columns=["best_name", "office_name", "Í±∞Î¶¨Ï∞®Ïù¥", "score"])

for i in range(0, len(best_4_dict)) :
    best_nm = list(best_4_dict.keys())[i]
    best_xy = list(best_4_dict.items())[i][1]

    for j in range(0, len(office_dict)) :
        office_nm = list(office_dict.keys())[j]
        office_xy = list(office_dict.items())[j][1]

        ## ÏµúÏ¢Ö Í±∞Î¶¨ Í≥ÑÏÇ∞ Í≤∞Í≥ºÍ∞í
        result = haversine(best_xy, office_xy, unit='m')

        score = 0
        if result <= 200:
            score = 5
        elif 200 < result <= 400:
            score = 4
        elif 400 < result <= 600:
            score = 3
        elif 600 < result <= 800:
            score = 2
        elif 800 < result <= 1000:
            score = 1
        df_all = pd.concat([df_all, 
                        pd.DataFrame({'best_name':[best_nm],'office_name':[office_nm], 'Í±∞Î¶¨Ï∞®Ïù¥':[result], 'score':[score]})], ignore_index=True)
df_all

      best_name office_name          Í±∞Î¶¨Ï∞®Ïù¥ score
0      85094952        Ïö©Ïù∏ÏãúÏ≤≠   5899.879981     0
1      85094952        Ï≤òÏù∏Íµ¨Ï≤≠   7739.626588     0
2      85094952         Ìè¨Í≥°Ïùç  12039.810810     0
3      85094952         Î™®ÌòÑÏùç  16533.790770     0
4      85094952         ÎÇ®ÏÇ¨Î©¥  12025.162787     0
...         ...         ...           ...   ...
11020  84999068        Ï£ΩÏ†Ñ2Îèô   7005.076502     0
11021  84999068         ÎèôÏ≤úÎèô   8107.417622     0
11022  84999068        ÏÉÅÌòÑ1Îèô   4777.548586     0
11023  84999068        ÏÉÅÌòÑ2Îèô   5232.174523     0
11024  84999068         ÏÑ±Î≥µÎèô   6473.079070     0

[11025 rows x 4 columns]

In [65]:
df_all_4 = df_all.groupby('office_name')['score'].sum()
df_all_4 = df_all_4.reset_index()
df_all_4 = df_all_4.rename(columns = {'score' : '4_score'})
df_all_4

   office_name 4_score
0          Íµ¨Í∞àÎèô      17
1          Íµ¨ÏÑ±Îèô      27
2         Í∏∞Ìù•Íµ¨Ï≤≠      39
3          Í∏∞Ìù•Îèô       2
4          ÎÇ®ÏÇ¨Î©¥       0
5          ÎèôÎ∞±Îèô      18
6          ÎèôÎ∂ÄÎèô       4
7          ÎèôÏ≤úÎèô      33
8          ÎßàÎ∂ÅÎèô      21
9          Î™®ÌòÑÏùç       2
10         Î∞±ÏïîÎ©¥       3
11         Î≥¥Ï†ïÎèô      17
12         ÏÉÅÍ∞àÎèô      21
13         ÏÉÅÌïòÎèô      37
14        ÏÉÅÌòÑ1Îèô      39
15        ÏÉÅÌòÑ2Îèô      54
16         ÏÑúÎÜçÎèô      15
17         ÏÑ±Î≥µÎèô      45
18        ÏàòÏßÄÍµ¨Ï≤≠      37
19         Ïã†Í∞àÎèô      27
20         Ïã†Î¥âÎèô      33
21         ÏñëÏßÄÎ©¥      10
22         Ïó≠ÏÇºÎèô      26
23         ÏòÅÎçïÎèô      19
24        Ïö©Ïù∏ÏãúÏ≤≠      14
25         ÏõêÏÇºÎ©¥       4
26         Ïú†Î¶ºÎèô       7
27         Ïù¥ÎèôÏùç       0
28        Ï£ΩÏ†Ñ1Îèô      52
29        Ï£ΩÏ†Ñ2Îèô      46
30         Ï§ëÏïôÎèô      23
31        Ï≤òÏù∏Íµ¨Ï≤≠      39
32         Ìè¨Í≥°Ïùç       1
33       ÌíçÎçïÏ≤ú1Îèô      39
34       ÌíçÎçïÏ≤ú2Îèô      42